/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import controller.Controller;
import deepspace.EnemyToUI;
import deepspace.GameState;
import javax.swing.JPanel;

/**
 *
 * @author lauralazaro
 */
public class EnemyStarShipView extends JPanel {
    
    private LootView loot;
    private DamageView damage;

    /**
     * Creates new form EnemyStarShipView
     */
    public EnemyStarShipView() {
        initComponents();
        
        loot = new LootView();
        lootPanel.add(loot);
        
        damage = new DamageView();
        damagePanel.add(damage);
        
        repaint();
        revalidate();
    }
    
    public void setEnemyStarShip(EnemyToUI other) {
        enemy.setText(other.getName());
        firePower.setText(Float.toString(other.getAmmoPower()));
        shieldPower.setText(Float.toString(other.getShieldPower()));
      
        loot.setLoot(other.getLoot());
        damage.setDamage(other.getDamage());
        
        if (Controller.getInstance().getState() == GameState.BEFORECOMBAT || Controller.getInstance().getState() == GameState.INIT) {
            loot.setVisible(false);
            damage.setVisible(false);
        }
        else {
            loot.setVisible(true);
            damage.setVisible(true);
        }
        
        repaint();
        revalidate();
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enemyLabel = new javax.swing.JLabel();
        enemy = new javax.swing.JLabel();
        firePowerLabel = new javax.swing.JLabel();
        shieldPowerLabel = new javax.swing.JLabel();
        firePower = new javax.swing.JLabel();
        shieldPower = new javax.swing.JLabel();
        lootPanel = new javax.swing.JPanel();
        damagePanel = new javax.swing.JPanel();

        enemyLabel.setText("Enemigo:");

        enemy.setText("jLabel1");

        firePowerLabel.setText("Potencia de fuego:");

        shieldPowerLabel.setText("Potencia de defensa:");

        firePower.setText("jLabel1");

        shieldPower.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(enemyLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enemy))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(firePowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firePower))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(shieldPowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shieldPower)))
                        .addGap(0, 148, Short.MAX_VALUE))
                    .addComponent(damagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enemyLabel)
                    .addComponent(enemy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firePowerLabel)
                    .addComponent(firePower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shieldPowerLabel)
                    .addComponent(shieldPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(damagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel damagePanel;
    private javax.swing.JLabel enemy;
    private javax.swing.JLabel enemyLabel;
    private javax.swing.JLabel firePower;
    private javax.swing.JLabel firePowerLabel;
    private javax.swing.JPanel lootPanel;
    private javax.swing.JLabel shieldPower;
    private javax.swing.JLabel shieldPowerLabel;
    // End of variables declaration//GEN-END:variables
}
