package View.GUI;


import deepspace.LootToUI;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lauralazaro
 */
public class LootView extends JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }
    
    public void setLoot (LootToUI loot) {
        weapons.setText(Integer.toString(loot.getnWeapons()));
        shields.setText(Integer.toString(loot.getnShields()));
        hangarSize.setText(Integer.toString(loot.getnHangars()));
        fuel.setText(Integer.toString(loot.getnSupplies()));
        medals.setText(Integer.toString(loot.getnMedals()));
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weaponsLabel = new javax.swing.JLabel();
        shieldsLabel = new javax.swing.JLabel();
        hangarSizeLabel = new javax.swing.JLabel();
        weapons = new javax.swing.JLabel();
        shields = new javax.swing.JLabel();
        hangarSize = new javax.swing.JLabel();
        fuelLabel = new javax.swing.JLabel();
        fuel = new javax.swing.JLabel();
        medalsLabel = new javax.swing.JLabel();
        medals = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botín", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(91, 91, 91))); // NOI18N

        weaponsLabel.setText("Armas:");

        shieldsLabel.setText("Escudos:");

        hangarSizeLabel.setText("Tamaño del Hangar:");

        weapons.setText("jLabel1");

        shields.setText("jLabel1");

        hangarSize.setText("jLabel1");

        fuelLabel.setText("Combustible:");

        fuel.setText("jLabel1");

        medalsLabel.setText("Medallas:");

        medals.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weaponsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weapons))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shieldsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shields))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hangarSizeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hangarSize))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fuelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fuel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(medalsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medals)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weaponsLabel)
                    .addComponent(weapons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shieldsLabel)
                    .addComponent(shields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hangarSizeLabel)
                    .addComponent(hangarSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelLabel)
                    .addComponent(fuel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medalsLabel)
                    .addComponent(medals))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fuel;
    private javax.swing.JLabel fuelLabel;
    private javax.swing.JLabel hangarSize;
    private javax.swing.JLabel hangarSizeLabel;
    private javax.swing.JLabel medals;
    private javax.swing.JLabel medalsLabel;
    private javax.swing.JLabel shields;
    private javax.swing.JLabel shieldsLabel;
    private javax.swing.JLabel weapons;
    private javax.swing.JLabel weaponsLabel;
    // End of variables declaration//GEN-END:variables
}
