/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.ShieldToUI;
import javax.swing.JPanel;

/**
 *
 * @author lauralazaro
 */
public class ShieldView extends JPanel implements CombatElementView {

    private boolean selected=false;
    /**
     * Creates new form ShieldView
     */
    public ShieldView() {
        initComponents();
        setOpaque(selected);
    }
    
    @Override
    public boolean getSelected() {
        return selected;
    }
    
    void setShield(ShieldToUI shield) {
        shieldPower.setText(Float.toString(shield.getBoost()));
        shieldUses.setText(Integer.toString(shield.getUses()));
        revalidate();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shieldPowerLabel = new javax.swing.JLabel();
        shieldUsesLabel = new javax.swing.JLabel();
        shieldPower = new javax.swing.JLabel();
        shieldUses = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        shieldPowerLabel.setText("Potencia:");

        shieldUsesLabel.setText("Usos:");

        shieldPower.setText("jLabel1");

        shieldUses.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shieldPowerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shieldPower))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shieldUsesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shieldUses)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shieldPowerLabel)
                    .addComponent(shieldPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shieldUsesLabel)
                    .addComponent(shieldUses))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selected = !selected;
        setOpaque (selected);
        repaint();
        revalidate();
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel shieldPower;
    private javax.swing.JLabel shieldPowerLabel;
    private javax.swing.JLabel shieldUses;
    private javax.swing.JLabel shieldUsesLabel;
    // End of variables declaration//GEN-END:variables
}
