/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.WeaponToUI;
import javax.swing.JPanel;

/**
 *
 * @author lauralazaro
 */
public class WeaponView extends JPanel implements CombatElementView {

    private boolean selected = false;
    
    /**
     * Creates new form WeaponView
     */
    public WeaponView() {
        initComponents();
        setOpaque(selected);
    }
    
    @Override
    public boolean getSelected () {
        return selected;
    }
    
    void setWeapon(WeaponToUI weapon) {
        weaponType.setText(weapon.getType().toString());
        weaponUses.setText(Integer.toString(weapon.getUses()));
        weaponAmmoPower.setText(Float.toString(weapon.getPower()));
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weaponTypeLabel = new javax.swing.JLabel();
        weaponAmmoPowerLabel = new javax.swing.JLabel();
        weaponUsesLabel = new javax.swing.JLabel();
        weaponType = new javax.swing.JLabel();
        weaponUses = new javax.swing.JLabel();
        weaponAmmoPower = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        weaponTypeLabel.setText("Tipo:");

        weaponAmmoPowerLabel.setText("Potencia:");

        weaponUsesLabel.setText("Usos:");

        weaponType.setText("jLabel1");

        weaponUses.setText("jLabel1");

        weaponAmmoPower.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weaponTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weaponType))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weaponAmmoPowerLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weaponAmmoPower))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weaponUsesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weaponUses)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weaponTypeLabel)
                    .addComponent(weaponType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weaponAmmoPowerLabel)
                    .addComponent(weaponAmmoPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weaponUsesLabel)
                    .addComponent(weaponUses))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selected = !selected;
        setOpaque (selected);
        repaint();
        revalidate();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel weaponAmmoPower;
    private javax.swing.JLabel weaponAmmoPowerLabel;
    private javax.swing.JLabel weaponType;
    private javax.swing.JLabel weaponTypeLabel;
    private javax.swing.JLabel weaponUses;
    private javax.swing.JLabel weaponUsesLabel;
    // End of variables declaration//GEN-END:variables
}
